-- Definir qual banco de dados vamos utilizar
USE AULA_BDI_221;
GO

--PERGUNTAS

--1 QUAIS SÃO OS PRODUTOS COM VALOR MENOR QUE 100 REAIS? MOSTRE TODAS AS INFORMAÇÕES DOS PRODUTOS COM ESSA CARACTERÍSTICA.
SELECT * FROM DBO.PRODUTO WHERE VALOR < 100;

--2 QUAIS SÃO OS NOMES DOS PETS QUE TÊM PORTE PEQUENO? MOSTRE APENAS P NOME DO PET E O PORTE.
SELECT NOME, PORTE FROM PET
GROUP BY NOME, PORTE
HAVING PORTE = 'P';

--3 QUAL É A ORDEM CRESCENTE DOS SALÁRIOS DOS FUNCIONÁRIOS? MOSTRE APENAS OS VALORES DOS SALÁRIOS.
SELECT SALARIO FROM FUNCIONARIO ORDER BY SALARIO;

--4 QUAIS OS PETS DE CADA CLIENTE? (CASO O CLIENTE TENHA PET CADASTRADO)
SELECT
	C.ID AS ID_CLIENTE,
	P.NOME AS NOME_PET
FROM CLIENTE_PET AS C
INNER JOIN PET AS P
	ON C.ID_PET = P.ID;

--5 QUAIS AS FORMAS DE PAGAMENTO DE CADA VENDA?
SELECT
	V.ID AS ID_VENDA,
	FP.DESCRICAO AS DESCRICAO_FORMA_PAGAMENTO
FROM VENDA AS V
INNER JOIN FORMA_PAGAMENTO AS FP
	ON V.ID_FORMA_PAGAMENTO = FP.ID;

--6 QUAIS FORAM AS VENDAS QUE FORAM FEITAS DO TIPO 'S', OU SEJA, COMO SERVIÇO?
SELECT
	V.ID AS ID_VENDA,
	TP.TIPO AS TIPO_PRODUTO
FROM PRODUTO_VENDA AS V
INNER JOIN PRODUTO AS TP
	ON V.ID_PRODUTO = TP.ID
WHERE TIPO = 'S';



--INSERINDO NA TABELA CLIENTE_PET
SELECT * FROM CLIENTE_PET;

DELETE FROM DBO.CLIENTE_PET;
DBCC CHECKIDENT ('CLIENTE_PET', RESEED, 0);
GO

INSERT INTO DBO.CLIENTE_PET VALUES(2, 1);
INSERT INTO DBO.CLIENTE_PET VALUES(6, 8);
INSERT INTO DBO.CLIENTE_PET VALUES(1, 4);
INSERT INTO DBO.CLIENTE_PET VALUES(12, 2);
INSERT INTO DBO.CLIENTE_PET VALUES(5, 3);
INSERT INTO DBO.CLIENTE_PET VALUES(10, 5);
INSERT INTO DBO.CLIENTE_PET VALUES(9, 6);
INSERT INTO DBO.CLIENTE_PET VALUES(4, 7);
INSERT INTO DBO.CLIENTE_PET VALUES(7, 9);
